GET http://localhost:3000/prefixo/hello

### 
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Produto 2",
    "slug": "produto-2",1
    "description": "Descrição do produto 2",
    "price": 10000
}

### 
GET http://localhost:3000/products/cm6mo53fi0000v1r0vfftpxri

###
PATCH http://localhost:3000/products/cm6mo53fi0000v1r0vfftpxri

###
DELETE http://localhost:3000/products/cm6mo53fi0000v1r0vfftpxri