GET http://localhost:3000/prefixo/hello

### 
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "slug": "product-10",
    "description": "Description of 1",
    "price": 100
}

### 
GET http://localhost:3000/products/cm6mo53fi0000v1r0vfftpxri

###
PATCH http://localhost:3000/products/cm6mo53fi0000v1r0vfftpxri
Content-Type: application/json

{
    "name": "Produto 555",
    "slug": "produto-555",
    "description": "Descrição do produto 5",
    "price": 65497
}

###
DELETE http://localhost:3000/products/cm6mwhd010000v12o03d4qr1n